id: IEE9AEEDB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:27:56+00:00'
last_modified: '2022-06-07T12:38:23.345701+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18110
  title: འོད་ཟེར་ཅན་མའི་དགྲ་སྒྲུབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F002:
      image_group_id: I8LS18142
      title: ''
      total_pages: 24
      order: 1
      base_file: F002.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
