id: P000677
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18110
  title: འོད་ཟེར་ཅན་མའི་དགྲ་སྒྲུབ།
  author: ''
  volumes:
    472224ed1c0149b39c639ee0f1478d69:
      image_group_id: I8LS18142
      title: ''
      volume_number: 1
      total_pages: 24
