id: P000677
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:36:35.076103
source_metadata:
  id: bdr:W8LS18110
  title: འོད་ཟེར་ཅན་མའི་དགྲ་སྒྲུབ།
  author: ''
  volumes:
    472224ed1c0149b39c639ee0f1478d69:
      image_group_id: I8LS18142
      title: ''
      volume_number: 1
      total_pages: 24
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
